plugins {
    id 'java'
}

group = 'dev.antiboatfly'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://repo.codemc.io/repository/maven-releases/' }
    maven { url = 'https://repo.codemc.io/repository/maven-snapshots/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT'
    compileOnly 'com.github.retrooper:packetevents-spigot:2.13.0'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    filteringCharset = 'UTF-8'
    filesMatching('plugin.yml') {
        expand(version: project.version)
    }
}

def serverPluginsDirectory = file('C:/Leap/SV/plugins')

tasks.register('deployPlugin', Copy) {
    dependsOn tasks.named('jar')
    from tasks.named('jar').flatMap { it.archiveFile }
    into serverPluginsDirectory
}

tasks.named('build') {
    finalizedBy tasks.named('deployPlugin')
}
